############################
## CHANGE THESE
############################

baseURL: "https://simplemindedbot.github.io/simplemindedrepo"
title: simplemindedrepo

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
